### PR TITLE
Add behat features checking empty project states

### PR DESCRIPTION
**Pull request by padraic**
See #169, #189 and #234

Need to check on Windows to see if these fail there. Work as expected on Ubuntu.

### CODE REVIEW

**Comment by theofidry** [comment]
@padraic you may want to _rebase_ instead of merging (with `-Xtheirs` to avoid stupid conflicts)

**Comment by theofidry** [comment]
Looks like there's a weird error on AppVeyor...

**Comment by padraic** [comment]
@theofidry It's #232 being pending, so it's not actually building for other PRs.

**Comment by theofidry** [comment]
Oh, I guess you can merge this one then :)

**Pull request merged**
