### PR TITLE
Basic PSR-2 error fixes from running phpcbf

### PR DESCRIPTION
**Pull request by padraic**
Adds additional PSR-2 fixes from implementing #240. PHP CodeSniffer is stricter than StyleCI, but usually for fairly inconsequential things. This just cleans those up so using `composer cs-check` doesn't explode.

### CODE REVIEW

**Comment by theofidry** [comment]
StyleCI is failing due to trailing spaces

**Comment by theofidry** [comment]
Not sure about the AppVeyor failure though, looks weird

**Comment by GrahamCampbell** [comment]
StyleCI will fix more things if you enable more fixers. The "recommended" preset is very good, and can be tweaked if needed.

**Comment by GrahamCampbell** [comment]
There are a small number of fixers that go slightly beyond PSR-2, so couldn't be included in the preset, but can be used to enforce a slightly stricter version of PSR-2.

**Comment by padraic** [comment]
@theofidry The Appveyor CI is pending #232 

@GrahamCampbell The SyleCI interpretation of PSR2 is fine. If anything, I'd go in the other direction and exclude a sniff or two from phpcs where it goes over the standard. I don't think I can selectively add an additional one though (phpcs is not spotting all trailing whitespace as my last commit fixed).

**Pull request merged**
