### PR TITLE
Fix mutants not covered issue

### PR DESCRIPTION
**Pull request by GM-Alex**
This PR fixes issue #151 that mutants are marked as not covered if they are covered.

@padraic Beside this PR please don't let humbug die and thanks for your awesome work so far. :)

### CODE REVIEW

**Comment by padraic** [comment]
I won't let it die :). I'm taking a gradual approach, but expect some updates on Humbug's future very soon.

**Comment by theofidry** [comment]
@GM-Alex would you mind adding a test for it? Although I'm not sure we have tests for the Tokenizer. If that's not the case, they I would be more comfortable to merge this one after a manual check by someone else (@padraic?)

**Comment by GM-Alex** [comment]
@theofidry & @padraic Currently I'm short of time so I'm not able to provide a test soon but the problem occurs if you have something like the following in your code:

```php
$myString = "This is my string
    which is very
    very long and
    has several line breaks."
```

**Comment by padraic** [comment]
@GM-Alex @humbug/core I added a quick behat features to replicate this, so the fix works perfectly. I've updated @GM-Alex's branch with two behat features which should now be passing (the multiline comment one is just to add coverage).

**Comment by padraic** [comment]
Thanks again, @GM-Alex. Sorry for the wait ;).

**Comment by GM-Alex** [comment]
@padraic Thanks a lot!

**Pull request merged**
