### PR TITLE
detect the name of traits

### PR DESCRIPTION
**Pull request by villfa**

### CODE REVIEW

**Comment by theofidry** [comment]
Seems ok but I wouldn't be surprised if there's something missing as this looks like an overly simplified example. @padraic would you mind taking a look?

**Comment by padraic** [comment]
It's more than likely okay since traits are just another high level structure along with classes/interfaces. So it should be a relatively simple file level check.

**Comment by padraic** [comment]
Travis CI fail on PHP 7 is expected. Not a blocker to merging.

**Comment by padraic** [comment]
Merging as trivial/obvious. Thanks @villfa!

**Pull request merged**
