### PR TITLE
Add Docker section to README.md

### PR DESCRIPTION
**Pull request by tommy-muehle**
Hi @padraic,

I'm dockerized Humbug for our local CI and want to share this installation/usage possibility.
So I'm updated the manual. All further informations can be find [here](https://hub.docker.com/r/dockerizedphp/humbug/).

sincerely Tommy

### CODE REVIEW

**Comment by theofidry** [comment]
Hi, while I appreciate the initiative, I'm a bit less sure about adding this unless we guarantee the support for docker.

Alternatively a mention under the title to warn that it's a third-party repo (i.e. support not guaranteed by the team) would be ok as well.

**Comment by padraic** [comment]
The problem is indeed is who controls this and maintains it. We could add as something to look into, but unless someone on the team is literally checking it regularly...

**Comment by theofidry** [comment]
@humbug/core thoughts? I would be for adding this in the README to provide some visibility to that project, but with a note saying we don't guarantee the support for it. I'm also in favour of not maintaining a docker repo for now, I think we have enough work :)

**Comment by tommy-muehle** [comment]
Hi guys,
I maintain all my repo's [here](https://github.com/dockerized-php) and do the same for the [PHPStan Docker image](https://github.com/phpstan/docker-image). I'm watching releases via RSS feed and updates the images if is necessary.
And in case you're interested, I can also move the humbug Docker image in your new organization account and maintain it as a collaborator.

**Comment by MarkRedeman** [comment]
I think this is a good idea, but users do have to be careful that the php version used in the Docker container matches the version that they use in their application (including extensions etc needed for their (unit) tests).
Otherwise Humbug might give false positives since tests might fail in a newer / older version of php.
We could fix that issue by having an option in Humbug to choose the php binary that is used to run phpunit et al, though I'm not quite sure how we could integrate that in a Docker container.

**Comment by tommy-muehle** [comment]
@MarkRedeman 
The goal of Docker is to provide a container in which everything is prepared to run one service, like humbug. 

So currently my image contains PHP 7.1 with xdebug, bz2 and PHPUnit 5.7 to run humbug inside.

I can provide a few more tags, so that the user's can select between
PHP 7.1 with xdebug,gzip + PHPUnit 6 (latest) + Humbug (latest)
PHP 7.1 with xdebug,gzip + PHPUnit 5 (latest) + Humbug (latest)
or
PHP 7.0 with xdebug,gzip + PHPUnit 6 (latest) + Humbug (latest)
PHP 7.0 with xdebug,gzip + PHPUnit 5 (latest) + Humbug (latest)

Otherwise you must extend the Docker image and prepare it for your needs. 
For example if you need a further extension like soap which is not enabled by default in the official PHP Docker image. I can also write a documentation section for this case.

**Comment by tommy-muehle** [comment]
Sorry guy's, I'll close this issue because in the meantime my focus are switched to other projects.
But many thanks for providing humbug!

**Comment by theofidry** [comment]
No worries :)

**Pull request closed without merging**
